<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="Utah.Udot.Atspm.Infrastructure" Version="5.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\Options\" />
    <Folder Include="Configuration\" />
    <Folder Include="BackgroundServices\" />
    <Folder Include="LogMessages\" />
  </ItemGroup>

	<ItemGroup>
		<None Update="appsettings*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.Development.json">
			<DependentUpon>appsettings.json</DependentUpon>
		</None>
		<None Update="appsettings.Staging.json">
			<DependentUpon>appsettings.json</DependentUpon>
		</None>
		<None Update="appsettings.Production.json">
			<DependentUpon>appsettings.json</DependentUpon>
		</None>
	</ItemGroup>

</Project>
